//this will process all the AST's generated byAST processing engine

import { extractMetadata } from "./metadata.service.js";

const processMetadata = (asts) => {
  const metadata = [];

  for (const ast of asts) {
    metadata.push({
      filePath: ast.filePath,
      metadata: extractMetadata(ast.tree),
    });
  }

  return metadata;
};

export { processMetadata };